# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ericbreh/school/cse293-final-project/eth_project/eth_project.srcs/sources_1/bd/design_1/ip/design_1_axis_snoop_debug_0_0/design_1_axis_snoop_debug_0_0.xci
# IP: The module: 'design_1_axis_snoop_debug_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ericbreh/school/cse293-final-project/eth_project/eth_project.gen/sources_1/bd/design_1/ip/design_1_axis_snoop_debug_0_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: /home/ericbreh/school/cse293-final-project/eth_project/eth_project.srcs/sources_1/bd/design_1/ip/design_1_axis_snoop_debug_0_0/design_1_axis_snoop_debug_0_0.xci
# IP: The module: 'design_1_axis_snoop_debug_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ericbreh/school/cse293-final-project/eth_project/eth_project.gen/sources_1/bd/design_1/ip/design_1_axis_snoop_debug_0_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet
