# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ericbreh/school/cse293-final-project/Toolbox/utils/xdc/Nexys-A7-100T-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rmii_axis_0_0/design_1_rmii_axis_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rmii_axis_0_0 || ORIG_REF_NAME==design_1_rmii_axis_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_gpio_0_0/design_1_axis_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_gpio_0_0 || ORIG_REF_NAME==design_1_axis_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_snoop_debug_0_0/design_1_axis_snoop_debug_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_snoop_debug_0_0 || ORIG_REF_NAME==design_1_axis_snoop_debug_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_uart_0_0/design_1_axis_uart_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_uart_0_0 || ORIG_REF_NAME==design_1_axis_uart_0_0} -quiet] -quiet

# XDC: /home/ericbreh/school/cse293-final-project/eth_project/eth_project.gen/sources_1/bd/design_1/design_1_ooc.xdc
