# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ericbreh/Documents/school/cse293-final-project/block-diagram-example/block-diagram-example.srcs/sources_1/bd/design_1/ip/design_1_axis_gpio_0_0/design_1_axis_gpio_0_0.xci
# IP: The module: 'design_1_axis_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ericbreh/Documents/school/cse293-final-project/block-diagram-example/block-diagram-example.gen/sources_1/bd/design_1/ip/design_1_axis_gpio_0_0/src/axis_data_fifo_tuser/axis_data_fifo_tuser.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_tuser || ORIG_REF_NAME==axis_data_fifo_tuser} -quiet] -quiet

# IP: /home/ericbreh/Documents/school/cse293-final-project/block-diagram-example/block-diagram-example.srcs/sources_1/bd/design_1/ip/design_1_axis_gpio_0_0/design_1_axis_gpio_0_0.xci
# IP: The module: 'design_1_axis_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ericbreh/Documents/school/cse293-final-project/block-diagram-example/block-diagram-example.gen/sources_1/bd/design_1/ip/design_1_axis_gpio_0_0/src/axis_data_fifo_tuser/axis_data_fifo_tuser.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_tuser || ORIG_REF_NAME==axis_data_fifo_tuser} -quiet] -quiet
